---
- name: register non-default repositories for the package manager
  template:
    src: extra_repositories.j2
    dest: /etc/yum.repos.d/origin_ci_tool_extras.repo

- name: register dependency repositories from the OpenShift public mirror
  get_url:
    url: https://mirror.openshift.com/pub/openshift-origin/nightly/rhel-7/dependencies/openshift-rhel7-dependencies.repo
    dest: /etc/yum.repos.d/openshift-rhel7-dependencies.repo

- name: register EPEL repositories for CentOS and RHEL
  command: '{{ ansible_pkg_mgr }} install epel-release'
  when: ansible_distribution in ['Red Hat Enterprise Linux', 'CentOS']