---
- name: add the signing key for the Google Chrome repository
  rpm_key:
    key: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: register the non-default repositories we need
  include: register_repositories.yml

- name: configure the package manager
  include: configure_yum.yml

- name: ensure systemd journal has persistent logs
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: '^Storage='
    line: 'Storage=persistent'
    state: present
    create: true

- name: restart the journal
  systemd:
    service: 'systemd-journald'
    state: 'restarted'