---
- name: update the SSH configuration to remove Vagrant specifics
  blockinfile:
    dest: '{{ ansible_env.HOME }}/.ssh/config'
    state: absent

- name: tear down the old VM
  command: "/usr/bin/vagrant destroy --force"
  args:
    chdir: '{{ origin_ci_vagrant_home_dir }}'