---
- name: ensure we have the parameters necessary to install Docker
  hosts: 'localhost'
  connection: 'local'
  become: no
  gather_facts: no

  pre_tasks:
    - name: ensure all required variables are set
      fail:
        msg: 'This playbook requires {{ item }} to be set.'
      when: item not in vars and item not in hostvars[inventory_hostname]
      with_items:
        - origin_ci_hosts
        - origin_ci_connection
        - origin_ci_docker_volume_group

- name: install Docker on a new host
  hosts: '{{ origin_ci_hosts }}'
  connection: '{{ origin_ci_connection }}'
  become: yes
  become_user: root

  pre_tasks:
#     Fedora `dnf` requires the epoch incorrectly, so we must
#     provide it: https://bugzilla.redhat.com/show_bug.cgi?id=1286877
#     Furthermore, `yum` *requires* an arch when an epoch is present,
#     so we additionally accept any arch, but must literally do so
#     with a glob suffix.
    - name: register origin_ci_isolated_package_version to account for epoch weirdness with Fedora and DNF
      set_fact:
        origin_ci_isolated_package_version: '2:{{ origin_ci_docker_version }}*'
      when: ansible_distribution == 'Fedora' and origin_ci_docker_version is defined

    - name: register origin_ci_isolated_package_version
      set_fact:
        origin_ci_isolated_package_version: '{{ origin_ci_docker_version }}'
      when: ansible_distribution != 'Fedora' and origin_ci_docker_version is defined

    - name: register origin_ci_isolated_disabledrepos
      set_fact:
        origin_ci_isolated_disabledrepos: '{{ origin_ci_docker_disabledrepos }}'
      when: origin_ci_docker_disabledrepos is defined

    - name: register origin_ci_docker_enabledrepos
      set_fact:
        origin_ci_isolated_enabledrepos: '{{ origin_ci_docker_enabledrepos }}'
      when: origin_ci_docker_enabledrepos is defined

    - name: register origin_ci_isolated_tmp_repourls
      set_fact:
        origin_ci_isolated_tmp_repourls: '{{ origin_ci_docker_tmp_repourls }}'
      when: origin_ci_docker_tmp_repourls is defined

  roles:
    - role: isolated-install
      origin_ci_isolated_package_name: 'docker'
    - role: docker