---
origin_ci_extra_repositories: |
  [
    {
      'header': 'google-chrome-stable',
      'name': 'Google Chrome Stable',
      'baseurl': [
        'http://dl.google.com/linux/chrome/rpm/stable/x86_64'
      ],
      'enabled': '1',
      'distributions': [
        'Red Hat Enterprise Linux',
        'CentOS',
        'Fedora'
      ]
    },
    {
      'header': 'rhel-7-server-ose-3.1-rpms',
      'name': 'RHEL7 Red Hat Atomic OpenShift 3.1',
      'baseurl': [
        'https://mirror.ops.rhcloud.com/enterprise/enterprise-3.1/RH7-RHAOS-3.1/x86_64/os/',
        'https://use-mirror1.ops.rhcloud.com/enterprise/enterprise-3.1/RH7-RHAOS-3.1/x86_64/os/',
        'https://use-mirror2.ops.rhcloud.com/enterprise/enterprise-3.1/RH7-RHAOS-3.1/x86_64/os/',
        'https://euw-mirror1.ops.rhcloud.com/enterprise/enterprise-3.1/RH7-RHAOS-3.1/x86_64/os/'
      ],
      'enabled': '1',
      'gpgcheck': '0',
      'gpgkey': [
        'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release',
        'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta',
        'https://mirror.ops.rhcloud.com/libra/keys/RPM-GPG-KEY-redhat-openshifthosted'
      ],
      'failovermethod': 'priority',
      'sslverify': '0',
      'sslclientcert': '/var/lib/yum/client-cert.pem',
      'sslclientkey': '/var/lib/yum/client-key.pem',
      distributions: [
        'Red Hat Enterprise Linux'
      ]
    },
    {
      'header': 'rhel-7-server-ose-3.2-rpms',
      'name': 'RHEL7 Red Hat Atomic OpenShift 3.2',
      'baseurl': [
        'https://mirror.ops.rhcloud.com/enterprise/enterprise-3.2/RH7-RHAOS-3.2/x86_64/os/',
        'https://use-mirror1.ops.rhcloud.com/enterprise/enterprise-3.2/RH7-RHAOS-3.2/x86_64/os/',
        'https://use-mirror2.ops.rhcloud.com/enterprise/enterprise-3.2/RH7-RHAOS-3.2/x86_64/os/',
        'https://euw-mirror1.ops.rhcloud.com/enterprise/enterprise-3.2/RH7-RHAOS-3.2/x86_64/os/'
      ],
      'enabled': '1',
      'gpgcheck': '0',
      'gpgkey': [
        'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release',
        'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta',
        'https://mirror.ops.rhcloud.com/libra/keys/RPM-GPG-KEY-redhat-openshifthosted'
      ],
      'failovermethod': 'priority',
      'sslverify': '0',
      'sslclientcert': '/var/lib/yum/client-cert.pem',
      'sslclientkey': '/var/lib/yum/client-key.pem',
      distributions: [
        'Red Hat Enterprise Linux'
      ]
    },
    {
      'header': 'rhel-7-server-ose-3.3-rpms',
      'name': 'RHEL7 Red Hat Atomic OpenShift 3.3',
      'baseurl': [
        'https://mirror.ops.rhcloud.com/enterprise/enterprise-3.3/RH7-RHAOS-3.3/x86_64/os/',
        'https://use-mirror1.ops.rhcloud.com/enterprise/enterprise-3.3/RH7-RHAOS-3.3/x86_64/os/',
        'https://use-mirror2.ops.rhcloud.com/enterprise/enterprise-3.3/RH7-RHAOS-3.3/x86_64/os/',
        'https://euw-mirror1.ops.rhcloud.com/enterprise/enterprise-3.3/RH7-RHAOS-3.3/x86_64/os/'
      ],
      'enabled': '1',
      'gpgcheck': '0',
      'gpgkey': [
        'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release',
        'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta',
        'https://mirror.ops.rhcloud.com/libra/keys/RPM-GPG-KEY-redhat-openshifthosted'
      ],
      'failovermethod': 'priority',
      'sslverify': '0',
      'sslclientcert': '/var/lib/yum/client-cert.pem',
      'sslclientkey': '/var/lib/yum/client-key.pem',
      distributions: [
        'Red Hat Enterprise Linux'
      ]
    }
  ]
