---
- name: ensure we have the parameters necessary to initialize the inventory
  hosts: 'localhost'
  connection: 'local'
  become: no
  gather_facts: no

  pre_tasks:
    - name: ensure all required variables are set
      fail:
        msg: 'This playbook requires {{ item }} to be set.'
      when: item not in vars and item not in hostvars[inventory_hostname]
      with_items:
        - origin_ci_inventory_dir

- name: set up the local inventory directory
  hosts: 'localhost'
  connection: 'local'
  become: no

  roles:
    - role: inventory