---
- name: ensure we have the parameters necessary to bring up the Vagrant VM
  hosts: 'localhost'
  connection: 'local'
  become: no
  gather_facts: no

  pre_tasks:
    - name: ensure all required variables are set
      fail:
        msg: 'This playbook requires {{ item }} to be set.'
      when: item not in vars and item not in hostvars[inventory_hostname]
      with_items:
        - origin_ci_vagrant_home_dir
        - origin_ci_vagrant_os
        - origin_ci_vagrant_provider
        - origin_ci_vagrant_stage
        - origin_ci_vagrant_ip
        - origin_ci_inventory_dir
        - origin_ci_ssh_config_strategy

- name: provision a local VM with Vagrant
  hosts: 'localhost'
  connection: 'local'
  become: no

  roles:
    - role: inventory
    - role: vagrant-up