---
- name: ensure the call to this playbook is well-formed
  hosts: 'localhost'
  connection: 'local'
  become: no
  gather_facts: no

  pre_tasks:
    - name: ensure all required variables are set
      fail:
        msg: 'This playbook requires {{ item }} to be set.'
      when: item not in vars and item not in hostvars[inventory_hostname]
      with_items:
        - origin_ci_vagrant_home_dir
        - origin_ci_vagrant_os
        - origin_ci_vagrant_provider
        - origin_ci_vagrant_stage
        - origin_ci_vagrant_ip

- name: provision a local VM with Vagrant
  hosts: 'localhost'
  connection: 'local'
  become: no

  roles:
    - role: vagrant-up

- name: ensure that the vagrant user has necessary privileges
  hosts: '{{ origin_ci_vagrant_hostname }}'
  connection: '{{ origin_ci_connection }}'
  become: yes
  become_user: root

  tasks:
    - name: ensure the vagrant user that we connect as can change to other users
      lineinfile:
        dest: /etc/sudoers.d/vagrant-nopasswd
        regexp: '^{{ ansible_env.SUDO_USER }}'
        line: '{{ ansible_env.SUDO_USER }}  ALL=(ALL)  NOPASSWD: ALL'
        state: present
        create: true