---
- name: ensure the call to this playbook is well-formed
  hosts: 'localhost'
  connection: 'local'
  become: no
  gather_facts: no

  pre_tasks:
    - name: ensure all required variables are set
      fail:
        msg: 'This playbook requires {{ item }} to be set.'
      when: item not in hostvars[inventory_hostname]
      with_items:
        - origin_ci_vagrant_home_dir
        - origin_ci_vagrant_os
        - origin_ci_vagrant_provider
        - origin_ci_vagrant_stage
        - origin_ci_vagrant_ip

- name: provision a local VM with Vagrant
  hosts: 'localhost'
  connection: 'local'
  become: no

  roles:
    - role: vagrant-up