---
- name: install Golang
  include: isolated-install/tasks/main.yml
  vars:
    origin_ci_isolated_package: golang-{{ origin_ci_golang_version[ansible_distribution] }}
    origin_ci_isolated_disabledrepos: *
    origin_ci_isolated_enabledrepos: {{ origin_ci_golang_repositories[ansible_distribution] | join(',') }}
    origin_ci_isolated_tmp_repourls: origin_ci_golang_tmp_repourls
