---
- name: Create docker-storage-setup sysconfig
  file:
    path: /etc/sysconfig/docker-storage-setup
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
    state: touch

- name: Set VG for docker-storage-setup
  ini_file:
    dest: /etc/sysconfig/docker-storage-setup
    section: Global
    option: VG
    value: "{{ origin_ci_docker_volume_group }}"

- name: Run docker-storage-setup
  command: docker-storage-setup
